#!/usr/bin/env node

/**
 * SearXNG MCP Server - Interactive Setup Wizard
 * Simple setup for non-technical users
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const SEPARATOR = '='.repeat(60);

function question(query) {
    return new Promise(resolve => rl.question(query, resolve));
}

async function main() {
    console.log(SEPARATOR);
    console.log('   SearXNG MCP Server - Setup Wizard');
    console.log(SEPARATOR);
    console.log('');
    console.log('This wizard will help you set up the server in 3 easy steps!');
    console.log('');

    // Step 1: Check Node.js
    console.log('Step 1/3: Checking Node.js...');
    const nodeVersion = process.version;
    console.log(`✅ Node.js ${nodeVersion} is installed`);
    console.log('');

    // Step 2: Check Python
    console.log('Step 2/3: Checking Python...');
    const pythonCommands = ['python3', 'python'];
    let pythonCmd = null;
    
    for (const cmd of pythonCommands) {
        try {
            const result = require('child_process').spawnSync(cmd, ['--version'], { 
                stdio: 'pipe',
                encoding: 'utf-8'
            });
            
            if (result.status === 0) {
                pythonCmd = cmd;
                const version = result.stdout.trim() || result.stderr.trim();
                console.log(`✅ Python is installed: ${version}`);
                break;
            }
        } catch (e) {
            // Continue
        }
    }
    
    if (!pythonCmd) {
        console.log('❌ Python is not installed');
        console.log('');
        console.log('Please install Python 3.9 or newer from:');
        console.log('   https://www.python.org/downloads/');
        console.log('');
        console.log('After installing Python, run this setup again.');
        rl.close();
        process.exit(1);
    }
    console.log('');

    // Step 3: Configuration
    console.log('Step 3/3: Configuration');
    console.log('');
    console.log('The server needs to know where your SearXNG instance is running.');
    console.log('');

    const defaultSearxng = 'http://localhost:32768';
    const defaultPort = '32769';
    const defaultTimezone = 'UTC';

    console.log(`Press Enter to use default values, or type your own:`);
    console.log('');

    const searxngUrl = await question(`SearXNG URL [${defaultSearxng}]: `);
    const port = await question(`Server Port [${defaultPort}]: `);
    const timezone = await question(`Timezone [${defaultTimezone}] (e.g., Asia/Seoul, America/New_York): `);

    const finalSearxng = searxngUrl.trim() || defaultSearxng;
    const finalPort = port.trim() || defaultPort;
    const finalTimezone = timezone.trim() || defaultTimezone;

    console.log('');
    console.log('Creating configuration file...');

    // Create .env file
    const envContent = `# SearXNG MCP Server Configuration
# Generated by setup wizard

SEARXNG_BASE_URL=${finalSearxng}
HOST=127.0.0.1
PORT=${finalPort}
DESIRED_TIMEZONE=${finalTimezone}
CONTENT_MAX_LENGTH=10000
SEARCH_RESULT_LIMIT=10
`;

    fs.writeFileSync('.env', envContent);
    console.log('✅ Configuration saved to .env');
    console.log('');

    console.log(SEPARATOR);
    console.log('   Setup Complete!');
    console.log(SEPARATOR);
    console.log('');
    console.log('Your server is configured:');
    console.log(`   SearXNG URL: ${finalSearxng}`);
    console.log(`   Server URL: http://127.0.0.1:${finalPort}`);
    console.log(`   Timezone: ${finalTimezone}`);
    console.log('');
    console.log('To start the server:');
    console.log('   • Windows: Double-click start.bat');
    console.log('   • Mac/Linux: Double-click start.sh (or run: ./start.sh)');
    console.log('   • Or run: npx .');
    console.log('');
    console.log('Configure your MCP client with:');
    console.log('   {');
    console.log('     "searxng-enhanced": {');
    console.log(`       "url": "http://127.0.0.1:${finalPort}",`);
    console.log('       "type": "http",');
    console.log('       "method": "sse"');
    console.log('     }');
    console.log('   }');
    console.log('');

    const startNow = await question('Would you like to start the server now? (y/n): ');

    rl.close();

    if (startNow.toLowerCase() === 'y' || startNow.toLowerCase() === 'yes') {
        console.log('');
        console.log('Starting server...');
        console.log('');

        // Load environment variables
        const env = {
            ...process.env,
            SEARXNG_BASE_URL: finalSearxng,
            HOST: '127.0.0.1',
            PORT: finalPort,
            DESIRED_TIMEZONE: finalTimezone
        };

        // Start the server
        const serverProcess = spawn('node', ['index.js'], {
            stdio: 'inherit',
            env: env
        });

        serverProcess.on('close', (code) => {
            if (code !== 0) {
                console.log('');
                console.log(`Server exited with code ${code}`);
            }
        });
    } else {
        console.log('You can start the server anytime using the start script!');
    }
}

main().catch(err => {
    console.error('Error:', err);
    rl.close();
    process.exit(1);
});
